// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Author struct {
	ID       string `json:"id"`
	Name     string `json:"name"`
	Bio      string `json:"bio"`
	Password string `json:"password"`
}

type Mutation struct {
}

type Query struct {
}

type NewAuthor struct {
	Name     string `json:"name"`
	Password string `json:"password"`
}
